version: '3.8'

services:
  insurance-claim-demo:
    image: openjdk:17-oracle
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "./mvnw clean install && java -jar target/insurance-claim-demo-1.0.0-SNAPSHOT.jar"
    ports:
      - "8080:8080"
    networks:
      - camunda

  risk:
    image: openjdk:17-oracle
    volumes:
      - ./risk:/app/risk
    working_dir: /app/risk
    command: bash -c "./mvnw clean install && java -jar target/risk-0.0.1-SNAPSHOT.jar"
    ports:
      - "8090:8090"
    networks:
      - camunda

  external_task_client:
    image: node:latest
    working_dir: /app/external_task_client
    volumes:
      - ./external_task_client:/app/external_task_client
    command: bash -c "npm install && npm start"
    networks:
      - camunda

networks:
    camunda:
        driver: bridge
